# Generated by Django 4.1.7 on 2023-04-17 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneroEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "GENEROS",
            },
        ),
        migrations.CreateModel(
            name="PeliculaEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "fecha_estreno",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("puntuacion", models.DecimalField(decimal_places=2, max_digits=4)),
                ("generos", models.ManyToManyField(to="peliculas.generoentity")),
            ],
            options={
                "db_table": "PELICULAS",
            },
        ),
    ]
