# Generated by Django 4.1.7 on 2023-06-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosInfo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosentity',
            name='info',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuariosInfo.usuariosinfoentity'),
        ),
    ]
